### ISSUE TITLE
Failing tests - test_coderunnerrepo.rb

### ISSUE THREAD

**Issue by ferdinandvanwyk** [edmundhighcock/coderunner#4]
Checking out the master branch and running

``` bash
rake test
```

produces the following error:

``` bash
TestCreate#test_create:
Git::GitExecuteError: git '--git-dir=/home/vanwyk/code/coderunner/test/createrepo/myrepo/.git' '--work-tree=/home/vanwyk/code/coderunner/test/createrepo/myrepo' rm '-f' '--' '/home/vanwyk/code/coderunner/test/createrepo/myrepo/sims/v/id_2/code_runner_info.rb'  2>&1:fatal: Could not switch to '/home/vanwyk/code/coderunner/test/createrepo/myrepo/sims/v/id_2/': No such file or directory
    /home/vanwyk/.rvm/gems/ruby-2.1.2/gems/git-1.2.9.1/lib/git/lib.rb:917:in `command'
    /home/vanwyk/.rvm/gems/ruby-2.1.2/gems/git-1.2.9.1/lib/git/lib.rb:529:in `remove'
    /home/vanwyk/.rvm/gems/ruby-2.1.2/gems/git-1.2.9.1/lib/git/base.rb:231:in `remove'
    /home/vanwyk/code/coderunner/lib/coderunner/instance_methods.rb:1582:in `block (2 levels) in destroy'
    /home/vanwyk/code/coderunner/lib/coderunner/instance_methods.rb:1582:in `each'
    /home/vanwyk/code/coderunner/lib/coderunner/instance_methods.rb:1582:in `block in destroy'
    /home/vanwyk/code/coderunner/lib/coderunner/instance_methods.rb:1581:in `chdir'
    /home/vanwyk/code/coderunner/lib/coderunner/instance_methods.rb:1581:in `destroy'
    /home/vanwyk/code/coderunner/test/test_coderunnerrepo.rb:61:in `block (2 levels) in test_create'
    /home/vanwyk/code/coderunner/test/test_coderunnerrepo.rb:56:in `chdir'
    /home/vanwyk/code/coderunner/test/test_coderunnerrepo.rb:56:in `block in test_create'
    /home/vanwyk/code/coderunner/test/test_coderunnerrepo.rb:38:in `chdir'
    /home/vanwyk/code/coderunner/test/test_coderunnerrepo.rb:38:in `test_create'
```

These are the offending lines:

``` ruby
Dir.chdir('myrepo/sims') do                                               
        CodeRunner.submit(C: 'cubecalc', m: 'empty', X: '../../cubecalc')       
        CodeRunner.submit(C: 'cubecalc', m: 'empty', X: '../../cubecalc')       
        r = CodeRunner.fetch_runner                                             
        r.conditions = 'id==2'                                                  
        r.destroy no_confirm: true                                              
        #CodeRunner.delete(j: 2)                                                
        FileUtils.touch('.code-runner-irb-save-history')                        
        Dummy.new.setup_interactive                                             
      end
```

It seems to not be completing the second submission, is that because it detected an identical run already in the run folder?

**Comment by edmundhighcock** [comment]
I've made a new branch for testing the coderunner repo functionality, and I've deleted the tests that relate to it from the master branch in commit 15c23606fcbfa95d4415b099233184dc2948eafa

**Comment by edmundhighcock** [comment]
`rake test` now passes for me

**Comment by ferdinandvanwyk** [comment]
It is passing for me as well. Closing this issue.
